baseURL = 'https://azrael-iii.github.io/portfolio.github.io/'
languageCode = 'fr-fr'
title = 'Portfolio'
theme = 'terminal'

[[menu.main]]
  name = "A propos"
  url = "/about"

[[menu.main]]
  name = "Veille Technologique"
  url = "/veille/veille"
  
[[menu.footer]]
  name = "A propos"
  url = "/about"

[markup.goldmark.renderer]
  unsafe= true

[params]
  enableEmoji= true
  themeColor = "green"
  fullWidthTheme = true
  updatedDatePrefix = "Mis à jour"
  Toc = true
  TocTitle = "Index"