baseURL = 'https://azrael-iii.github.io/portfolio.github.io/'
languageCode = 'en-us'
title = 'Portfolio'
theme = 'terminal'

[[menu.main]]
  name = "A propos"
  url = "/about"

[[menu.main]]
  name = "Veille Technologique"
  url = "/veille/veille"
  
[[menu.footer]]
  name = "A propos"
  url = "/about"

[markup.goldmark.renderer]
  unsafe= true

[params]
  enableEmoji= true
  themeColor = "green"
  fullWidthTheme = true
  updatedDatePrefix = "Mis à jour"
  Toc = true
  TocTitle = "Index"
  
[languages]
  [languages.en]
    languageName = "Français"
    title = "Portfolio"
    subtitle = ""
    owner = "Vincent Hascoet"
    keywords = ""
    copyright = ""
    menuMore = "Voir plus"
    readMore = "Lire plus"
    readOtherPosts = "Lire d'autres publications"
    newerPosts = "Publications récentes"
    olderPosts = "Anciennes publications"
    missingContentMessage = "Page non trouvée..."
    missingBackButtonLabel = "Retour à l'accueil"
    minuteReadingTime = "minutes de lecture"
    words = "mots"

    [languages.en.params.logo]
      logoText = "Portfolio"
      logoHomeLink = "/"
